blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Mahdisellami/Hrisa-Docs/tree/main/docs
    about: Check the documentation for guides and troubleshooting
  - name: Questions & Discussions
    url: https://github.com/Mahdisellami/Hrisa-Docs/discussions
    about: Ask questions and discuss ideas with the community
